'use client';
import Home from '../page';
import Link from 'next/link';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {ArrowLeft,BookOpen,FileText,LockKeyhole,LogOut,Search,Upload,Save,Trash2} from 'lucide-react';
type Doc={id:string;title:string;url:string;organization:string;kind:string;category:string;retrievedAt:string;characters:number;chunks:number};
export default function Admin(){
 const [testing,setTesting]=useState(false);
 const [authenticated,setAuthenticated]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState(''),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[editing,setEditing]=useState<{id:string;title:string;text:string}|null>(null),[confirmDelete,setConfirmDelete]=useState<string|null>(null);
 const api=useCallback(async function api<T=unknown>(path:string,options?:RequestInit):Promise<T>{
  const r=await fetch(path,{...options,cache:'no-store'});const data=await r.json() as {error?:string};
  if(r.status===401){setAuthenticated(false);setDocs([]);setEditing(null);}
  if(!r.ok)throw Error(data.error||'The request failed.');return data as T;
 },[]);
 const load=useCallback(async()=>{const data=await api<{documents:Doc[]}>('/api/library');setDocs(data.documents);},[api]);
 useEffect(()=>{let active=true;(async()=>{try{const r=await fetch('/api/admin/session',{cache:'no-store'});const data=await r.json() as {authenticated:boolean};if(active){setAuthenticated(data.authenticated);if(data.authenticated)await load();}}catch{if(active)setError('Could not check your session. Reload to try again.');}finally{if(active)setChecking(false);}})();return()=>{active=false;};},[load]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});setPassword('');setAuthenticated(true);await load();}catch(e){setError(e instanceof Error?e.message:'Sign-in failed.');}finally{setBusy(false);}}
 async function logout(){setBusy(true);setError('');try{await api('/api/admin/session',{method:'DELETE'});setAuthenticated(false);setDocs([]);setEditing(null);setFile(null);setTitle('');setNotice('');}catch(e){setError(e instanceof Error?e.message:'Sign-out failed.');}finally{setBusy(false);}}
 async function upload(e:FormEvent){e.preventDefault();if(!file)return;setBusy(true);setError('');setNotice('');try{const form=new FormData();form.append('file',file);form.append('title',title);await api('/api/documents',{method:'POST',body:form});setFile(null);setTitle('');await load();setNotice('Document added. New questions can use it immediately.');}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}
 async function edit(id:string){setBusy(true);setError('');setNotice('');try{setEditing(await api<{id:string;title:string;text:string}>('/api/documents/'+id+'?format=text'));}catch(e){setError(e instanceof Error?e.message:'Could not open document.');}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setError('');try{await api('/api/documents/'+editing.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});setEditing(null);await load();setNotice('Changes saved. New answers will use the updated text.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError('');try{await api('/api/documents/'+id,{method:'DELETE'});setConfirmDelete(null);await load();setNotice('Document removed from future answers.');}catch(e){setError(e instanceof Error?e.message:'Removal failed.');}finally{setBusy(false);}}
 const shown=docs.filter(d=>(d.title+' '+d.organization+' '+d.category).toLowerCase().includes(query.toLowerCase()));
 if(authenticated&&testing)return <div className="admin-test-shell"><div className="admin-test-toolbar"><strong>Admin testing workspace</strong><span>Live knowledge base · Model diagnostics enabled</span><button onClick={()=>setTesting(false)}>Manage materials</button><button onClick={()=>void logout()}>Sign out</button></div><Home testMode/></div>;
 return <div className="admin-shell"><header className="admin-header"><Link href="/" className="admin-back"><ArrowLeft size={17}/> Student chat</Link><span>Ask SHC · Administration</span>{authenticated&&<button disabled={busy} onClick={()=>void logout()}><LogOut size={16}/> Sign out</button>}</header>
 <main className={'admin-content '+(!authenticated?'admin-login':'')}>
 {checking?<p role="status">Checking administrator session…</p>:!authenticated?<><LockKeyhole size={30} className="admin-symbol"/><h1>Administrator sign-in</h1><p>Test answers and manage the knowledge base.</p><form onSubmit={login}><label htmlFor="admin-password">Administrator password</label><input className="text-input" id="admin-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={512}/><button className="primary-button" disabled={busy||!password}>{busy?'Signing in…':'Sign in'}</button></form></>:<>
 <button className="primary-button admin-test-launch" onClick={()=>setTesting(true)}>Open test chat</button><div className="admin-title"><BookOpen size={26}/><div><h1>Supplementary materials</h1><p>{docs.length} sources · Administrators only</p></div></div>
 <p className="admin-explanation">Manage the evidence behind student answers. The library and full uploaded files are private to administrators. Relevant facts and cited excerpts can appear in student answers, so upload only material suitable for students.</p>
 {editing?<section className="admin-editor"><h2>Edit document</h2><form onSubmit={save}><label htmlFor="edit-title">Title</label><input id="edit-title" className="text-input" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} required maxLength={160}/><label htmlFor="edit-text">Source text</label><textarea id="edit-text" value={editing.text} onChange={e=>setEditing({...editing,text:e.target.value})} minLength={80} maxLength={250000} required rows={16}/><p className="upload-note">Saving replaces this document with a text version and updates the knowledge base immediately.</p><div className="admin-actions"><button className="primary-button" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save changes'}</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></form></section>:<section className="admin-upload"><h2>Add a document</h2><form onSubmit={upload}><label htmlFor="upload-title">Title <span>(optional)</span></label><input id="upload-title" className="text-input" value={title} onChange={e=>setTitle(e.target.value)} maxLength={160} placeholder="e.g. Updated resident guidance"/><label className="upload-zone"><Upload size={25}/><strong>{file?.name||'Choose a document'}</strong><span>Searchable PDF, TXT or Markdown · Up to 5 MB</span><input key={file?.name||'empty'} type="file" aria-label="Choose document" accept=".pdf,.txt,.md" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary-button" disabled={busy||!file}>{busy?'Processing…':'Add to knowledge base'}</button></form></section>}
 <section className="admin-library"><div className="admin-library-heading"><h2>Source collection</h2><label className="search-field"><Search size={17}/><input aria-label="Search supplementary materials" placeholder="Search title, category or organisation" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="upload-note">Official pages retain their original source. Upload updated notices to supplement them; uploaded text can be edited below.</p>
 {shown.map(d=><div className="admin-document" key={d.id}><FileText size={20}/><div className="admin-document-info"><strong>{d.title}</strong><small>{d.organization} · {d.kind} · {d.chunks} excerpts · Collected {d.retrievedAt}</small></div><div className="admin-actions"><a href={d.url} target="_blank" rel="noreferrer">{d.organization==='Uploaded'?'Download':'Original'}</a>{d.organization==='Uploaded'&&<><button disabled={busy} onClick={()=>void edit(d.id)}>Edit</button>{confirmDelete===d.id?<><button disabled={busy} onClick={()=>void remove(d.id)}>Confirm removal</button><button onClick={()=>setConfirmDelete(null)}>Cancel</button></>:<button disabled={busy} aria-label={'Remove '+d.title} onClick={()=>setConfirmDelete(d.id)}><Trash2 size={16}/></button>}</>}</div></div>)}{!shown.length&&<p className="empty">No matching documents. Try another search or add a source above.</p>}</section>
 </>}{error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}</main></div>;
}
