'use client';
import { readChatStream } from '../lib/chat-stream';
import { modelName } from '../lib/models';
import type { Attempt } from '../lib/openrouter';
import { useEffect,useRef,useState } from 'react';
import { ArrowUp,ArrowUpRight,BookOpen,Check,ChevronRight,FileText,Globe,HelpCircle,Library,LoaderCircle,MessageSquare,Plus,Search,Settings2,ShieldCheck,Trash2,Upload,X,Menu,Copy } from 'lucide-react';
type Source={id:string;title:string;url:string;organization:string;category:string;kind:string;retrievedAt:string;updatedLabel:string|null;historical:boolean;chunks?:number;characters?:number;text?:string;page?:number};
type Message={role:'user'|'assistant';content:string;sources?:Source[];error?:boolean;mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};
const attemptLabels:Record<string,string>={success:'Answer received',provider_rate_limit:'Provider rate limit',daily_quota:'Shared daily allowance reached',authentication:'Key or permission rejected',account_limit:'Account restriction',context_limit:'Context limit',output_limit:'Output limit',empty_answer:'Empty answer',provider_unavailable:'Provider unavailable',timeout_or_network:'Timed out or connection failed',invalid_citations:'Missing or invalid source citations'};
function ModelAttempts({message}:{message:Message}){
 if(!message.attempts?.length)return null;
 return <details className="model-attempts" open={message.mode==='document-only'||message.mode==='pending'||message.fallbackUsed}>
  <summary>Model attempts · {message.attempts.length+' tried'}</summary>
  <ol>{message.attempts.map((a,i)=><li key={i}><div><strong>{modelName(a.model)}</strong><span>{i===0?'First attempt':'Switched to other model'} · Free</span></div><div><span>{attemptLabels[a.reason]||'Request failed'}{a.status>0?' · Status '+a.status:''}</span><time dateTime={a.attemptedAt}>{new Date(a.attemptedAt).toLocaleTimeString('en-GB')}</time></div></li>)}</ol>
  {message.modelNotice&&<p>{message.modelNotice}</p>}
 </details>;
}
type ChatResult={error?:string;answer?:string;sources?:Source[];mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};
const suggestions=['What are the rules for visitors?','How do I apply for readmission?','Where can I do my laundry?','Can I use electrical appliances in my room?'];
export default function Home(){
 const [view,setView]=useState('chat'),[messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Source|null>(null),[menu,setMenu]=useState(false),[copied,setCopied]=useState(-1);
 const [pendingAttempts,setPendingAttempts]=useState<Attempt[]>([]);
 const end=useRef<HTMLDivElement>(null);const input=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'end'});},[messages,busy,pendingAttempts]);
 async function ask(q:string){if(busy||!q.trim())return;const previous=messages;setMessages([...previous,{role:'user',content:q.trim()}]);setQuestion('');setBusy(true);setPendingAttempts([]);setSelected(null);
  try{
   const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/x-ndjson'},body:JSON.stringify({message:q,history:previous.map(m=>({role:m.role,content:m.content}))})});
   const d:ChatResult=r.headers.get('content-type')?.includes('application/x-ndjson')?await readChatStream<ChatResult>(r,a=>setPendingAttempts(prev=>[...prev,a])):await r.json() as ChatResult;
   setMessages(m=>[...m,{role:'assistant',content:d.answer||d.error||'Please try again.',sources:d.sources||[],error:!r.ok||!!d.error,mode:d.mode,model:d.model,fallbackUsed:d.fallbackUsed,excerpts:d.excerpts,attempts:d.attempts,modelNotice:d.modelNotice}]);
  }catch{setMessages(m=>[...m,{role:'assistant',content:'The connection was interrupted. Please try again.',error:true}]);}finally{setBusy(false);setPendingAttempts([]);input.current?.focus();}}

 function go(next:string){setView(next);setMenu(false);setSelected(null);}
 const recentSources=messages.filter(m=>m.role==='assistant').at(-1)?.sources||[];
 function answerText(content:string,sources:Source[]=[]){return content.split(/(\[\d+\]|\*\*[^*]+\*\*)/g).map((part,i)=>{const n=part.match(/^\[(\d+)\]$/);if(n&&sources[Number(n[1])-1])return <button className="citation" key={i} aria-label={'View source '+n[1]} onClick={()=>setSelected(sources[Number(n[1])-1])}>{n[1]}</button>;if(part.startsWith('**'))return <strong key={i}>{part.slice(2,-2)}</strong>;return part;});}
 return <div className="app-shell">
 <a className="skip" href="#main">Skip to content</a>
 {menu&&<button className="mobile-shade" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
 <aside className={'sidebar '+(menu?'open':'')}>
  <a href="https://shunhingcollege.hku.hk/" target="_blank" rel="noreferrer" className="logo-window" aria-label="Shun Hing College official website"><img src="/shc-logo.png" alt="Shun Hing College, HKU"/></a>
  <div className="sidebar-title">Your college companion</div>
  <button className="new-chat" onClick={()=>{setMessages([]);setQuestion('');go('chat');input.current?.focus();}} disabled={busy}><Plus size={18}/> New conversation</button>
  <nav aria-label="Main navigation">
   <button className={view==='chat'?'active':''} onClick={()=>go('chat')}><MessageSquare size={19}/> Ask SHC <ChevronRight size={16}/></button>
  </nav>
  <div className="sidebar-info"><BookOpen size={21}/><p>College life comes<br/>with questions.</p><span>Find your answer, and the official source behind it.</span></div>
  <div className="sidebar-bottom"><a href="https://shunhingcollege.hku.hk/" target="_blank" rel="noreferrer">Shun Hing College <ArrowUpRight size={15}/></a><a href="https://jockeyv3.hku.hk/" target="_blank" rel="noreferrer">JCSV III website <ArrowUpRight size={15}/></a><div className="university">The University of Hong Kong</div></div>
 </aside>
 <div className="workspace">
  <header className="topbar"><div><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={21}/></button><span className="breadcrumb">Shun Hing College</span><ChevronRight size={14}/><strong>{view==='chat'?'Student help desk':view==='library'?'Source library':'Manage documents'}</strong></div><span className="preview-label">Preview</span></header>
  <div className="workarea"><main id="main" className={'main '+(view==='chat'?'chat-main':'')}>
   {view==='chat'&&<>
    <div className="chat-scroll">
    {!messages.length?<section className="welcome"><div className="assistant-mark" aria-hidden="true"><MessageSquare size={29}/></div><div className="welcome-label">ASK SHC</div><h1>A little clarity<br/>for college life.</h1><p>Ask about Shun Hing College and JCSV III.<br/>Get answers grounded in college documents.</p><div className="suggestions">{suggestions.map((s,i)=><button key={s} onClick={()=>void ask(s)}><span className="suggestion-icon">{i===0?<ShieldCheck size={18}/>:i===1?<BookOpen size={18}/>:i===2?<HelpCircle size={18}/>:<FileText size={18}/>}</span>{s}<ArrowUpRight size={16}/></button>)}</div></section>:<div className="conversation">{messages.map((m,i)=><article key={i} className={'message '+m.role}><div className="message-label">{m.role==='user'?'You':<><span className="mini-mark"><MessageSquare size={14}/></span>Ask SHC{m.mode==='document-only'&&<span className="document-mode"><BookOpen size={13}/> Document-only mode</span>}{m.error&&<span className="answer-status">Couldn’t complete answer</span>}</>}</div><div className="message-body">{answerText(m.content,m.sources)}</div>{m.excerpts?.map((excerpt,n)=><section className="quoted-evidence" key={n}><button onClick={()=>setSelected(m.sources?.[excerpt.sourceIndex-1]||null)}><BookOpen size={15}/>{excerpt.title}<span className="citation">{excerpt.sourceIndex}</span></button><blockquote>{excerpt.text}</blockquote></section>)}{m.sources?.length?<div className="source-chips">{m.sources.map((s,n)=><button key={s.id+n} onClick={()=>setSelected(s)}><span>{n+1}</span>{s.title.length>42?s.title.slice(0,42)+'…':s.title}</button>)}</div>:null}{m.role==='assistant'&&<ModelAttempts message={m}/>}{m.role==='assistant'&&<div className="message-actions">{m.model&&<span className="model-label">{modelName(m.model)} · Free{m.fallbackUsed?' · Fallback':null}</span>}<button onClick={async()=>{try{await navigator.clipboard.writeText(m.content+(m.excerpts?.length?"\n\n"+m.excerpts.map(e=>e.text+" ["+e.sourceIndex+"]").join("\n\n"):""));setCopied(i);setTimeout(()=>setCopied(-1),1800);}catch{setCopied(-1);}}}>{copied===i?<Check size={14}/>:<Copy size={14}/>} {copied===i?'Copied':'Copy answer'}</button>{m.error&&<button onClick={()=>void ask(messages[i-1]?.content||'')}>Try again</button>}</div>}</article>)}{busy&&<><div className="thinking" role="status"><LoaderCircle size={18} className="spin"/> {pendingAttempts.length?"Trying the next free model…":"Checking college documents and preparing your answer…"}</div><ModelAttempts message={{role:"assistant",content:"",mode:"pending",attempts:pendingAttempts}}/></>}<div ref={end}/></div>}
    </div>
    <div className="composer-area"><form className="composer" onSubmit={e=>{e.preventDefault();void ask(question);}}><textarea ref={input} aria-label="Your question" placeholder="What would you like to know?" value={question} maxLength={1500} rows={2} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(question);}}}/><div className="composer-footer"><span><BookOpen size={14}/> Answers with sources</span><button className="send" type="submit" disabled={busy||!question.trim()} aria-label="Send question">{busy?<LoaderCircle size={20} className="spin"/>:<ArrowUp size={21}/>}</button></div></form><p className="fine-print">AI can make mistakes. Check the cited documents for the official wording.</p></div>
   </>}
  </main>
  <aside className={'source-rail '+(selected?'has-selection':'')} aria-label="Source details">
   {selected?<><div className="rail-heading"><span>Source details</span><button aria-label="Close source details" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="source-detail"><span className="source-org">{selected.organization} · {selected.kind}</span><h2>{selected.title}</h2>{selected.page&&<p>Page {selected.page}</p>}<p className="source-date">Collected {selected.retrievedAt}{selected.updatedLabel&&<><br/>Source revision: {selected.updatedLabel}</>}</p>{selected.historical&&<div className="date-warning">This source is historical or date-sensitive. Check the academic year and any newer notices.</div>}{selected.text?<><h3>Retrieved excerpt</h3><blockquote>{selected.text}</blockquote></>:<p className="source-date">{selected.chunks} searchable excerpts · {selected.characters?.toLocaleString()} characters</p>}{selected.url&&<a className="source-link" href={selected.url+(selected.page&&selected.url.startsWith('http')?'#page='+selected.page:'')} target="_blank" rel="noreferrer">Open original source <ArrowUpRight size={16}/></a>}</div></>:<><div className="rail-heading"><span>{recentSources.length?'Sources for this answer':'Rooted in official sources'}</span><BookOpen size={17}/></div>{recentSources.length?<div className="rail-sources">{recentSources.map((s,i)=><button key={s.id+i} onClick={()=>setSelected(s)}><span>{i+1}</span><div><strong>{s.title}</strong><small>{s.organization}{s.page?' · Page '+s.page:''}</small></div><ChevronRight size={15}/></button>)}</div>:<><p className="rail-intro">A helpful answer should come with somewhere to check it.</p><a className="source-origin" href="https://shunhingcollege.hku.hk/" target="_blank" rel="noreferrer"><span className="origin-icon">SHC</span><span><strong>Shun Hing College</strong><small>College life, rules & admissions</small></span><ChevronRight size={15}/></a><a className="source-origin" href="https://jockeyv3.hku.hk/" target="_blank" rel="noreferrer"><span className="origin-icon village">III</span><span><strong>JCSV III</strong><small>Village facilities & regulations</small></span><ChevronRight size={15}/></a><div className="rail-topics"><h2>What you can ask about</h2>{['Rules & visitors','Facilities & everyday life','Admissions & fees','College teams & activities'].map(t=><div key={t}><Check size={15}/>{t}</div>)}</div><div className="collection-note"><span className="collection-line"/><strong>Official sources, one place.</strong><p>Collected from the official college and village websites. Sources retain their dates so older information stays in context.</p></div></>}<div className="rail-footer"><ShieldCheck size={18}/><p>A student information tool.<br/>College documents remain authoritative.</p></div></>}
  </aside></div>
 </div></div>;
}
