'use client';
import type { Attempt } from '../lib/openrouter';
import { useEffect,useRef,useState, type FormEvent } from 'react';
import { ArrowUp,ArrowUpRight,BookOpen,Check,ChevronRight,FileText,Globe,HelpCircle,Library,LoaderCircle,MessageSquare,Plus,Search,Settings2,ShieldCheck,Trash2,Upload,X,Menu,Copy } from 'lucide-react';
type Source={id:string;title:string;url:string;organization:string;category:string;kind:string;retrievedAt:string;updatedLabel:string|null;historical:boolean;chunks?:number;characters?:number;text?:string;page?:number};
type Message={role:'user'|'assistant';content:string;sources?:Source[];error?:boolean;mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};
const attemptLabels:Record<string,string>={success:'Answer received',provider_rate_limit:'Provider rate limit',daily_quota:'Shared daily allowance reached',authentication:'Key or permission rejected',account_limit:'Account restriction',context_limit:'Context limit',output_limit:'Output limit',empty_answer:'Empty answer',provider_unavailable:'Provider unavailable',timeout_or_network:'Timed out or connection failed'};
function ModelAttempts({message}:{message:Message}){
 if(!message.attempts?.length)return null;
 return <details className="model-attempts" open={message.mode==='document-only'||message.fallbackUsed}>
  <summary>Model attempts · {message.attempts.length===2?'Qwen + Gemma':message.attempts[0].model.includes('gemma')?'Gemma':'Qwen'}</summary>
  <ol>{message.attempts.map((a,i)=><li key={i}><div><strong>{a.model.includes('gemma')?'Gemma 4 31B':'Qwen3.8 27B'}</strong><span>{i===0?'First attempt':'Switched to other model'} · Free</span></div><div><span>{attemptLabels[a.reason]||'Request failed'}{a.status>0?' · Status '+a.status:''}</span><time dateTime={a.attemptedAt}>{new Date(a.attemptedAt).toLocaleTimeString('en-GB')}</time></div></li>)}</ol>
  {message.modelNotice&&<p>{message.modelNotice}</p>}
 </details>;
}
const suggestions=['What are the rules for visitors?','How do I apply for readmission?','Where can I do my laundry?','Can I use electrical appliances in my room?'];
export default function Home(){
 const [view,setView]=useState('chat'),[docs,setDocs]=useState<Source[]>([]),[messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState(''),[category,setCategory]=useState('All sources'),[selected,setSelected]=useState<Source|null>(null),[token,setToken]=useState(''),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[uploading,setUploading]=useState(false),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[copied,setCopied]=useState(-1),[pendingDelete,setPendingDelete]=useState<string|null>(null);
 const end=useRef<HTMLDivElement>(null);const input=useRef<HTMLTextAreaElement>(null);
 async function refresh(){try{const r=await fetch('/api/library');const d=await r.json() as {error?:string;documents:Source[];answer?:string;sources?:Source[];mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};if(!r.ok)throw Error(d.error);setDocs(d.documents);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load the library.');}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'end'});},[messages,busy]);
 async function ask(q:string){if(busy||!q.trim())return;const previous=messages;setMessages([...previous,{role:'user',content:q.trim()}]);setQuestion('');setBusy(true);setSelected(null);
  try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,history:previous.map(m=>({role:m.role,content:m.content}))})});const d=await r.json() as {error?:string;documents:Source[];answer?:string;sources?:Source[];mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};setMessages(m=>[...m,{role:'assistant',content:d.answer||d.error||'Please try again.',sources:d.sources||[],error:!r.ok,mode:d.mode,model:d.model,fallbackUsed:d.fallbackUsed,excerpts:d.excerpts,attempts:d.attempts,modelNotice:d.modelNotice}]);}catch{setMessages(m=>[...m,{role:'assistant',content:'The connection was interrupted. Please try again.',error:true}]);}finally{setBusy(false);input.current?.focus();}}
 function go(next:string){setView(next);setMenu(false);setSelected(null);}
 async function upload(e:FormEvent){e.preventDefault();if(!file)return;setUploading(true);setNotice('');const form=new FormData();form.append('file',file);form.append('title',title);
  try{const r=await fetch('/api/documents',{method:'POST',headers:{Authorization:'Bearer '+token},body:form});const d=await r.json() as {error?:string;documents:Source[];answer?:string;sources?:Source[];mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};if(!r.ok)throw Error(d.error);setNotice('Document added. It is now available in answers.');setFile(null);setTitle('');await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Upload failed.');}finally{setUploading(false);}}
 async function remove(id:string){try{const r=await fetch('/api/documents/'+id,{method:'DELETE',headers:{Authorization:'Bearer '+token}});if(!r.ok){const d=await r.json() as {error?:string;documents:Source[];answer?:string;sources?:Source[];mode?:string;model?:string;fallbackUsed?:boolean;attempts?:Attempt[];modelNotice?:string;excerpts?:{text:string;sourceIndex:number;title:string}[]};throw Error(d.error);}setPendingDelete(null);await refresh();setNotice('Document removed from the knowledge base.');}catch(e){setNotice(e instanceof Error?e.message:'Could not remove document.');}}
 const recentSources=messages.filter(m=>m.role==='assistant').at(-1)?.sources||[];
 const shown=docs.filter(d=>(category==='All sources'||d.organization===category||d.category===category)&&(d.title+' '+d.category+' '+d.organization).toLowerCase().includes(filter.toLowerCase()));
 function answerText(content:string,sources:Source[]=[]){return content.split(/(\[\d+\]|\*\*[^*]+\*\*)/g).map((part,i)=>{const n=part.match(/^\[(\d+)\]$/);if(n&&sources[Number(n[1])-1])return <button className="citation" key={i} aria-label={'View source '+n[1]} onClick={()=>setSelected(sources[Number(n[1])-1])}>{n[1]}</button>;if(part.startsWith('**'))return <strong key={i}>{part.slice(2,-2)}</strong>;return part;});}
 return <div className="app-shell">
 <a className="skip" href="#main">Skip to content</a>
 {menu&&<button className="mobile-shade" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
 <aside className={'sidebar '+(menu?'open':'')}>
  <a href="https://shunhingcollege.hku.hk/" target="_blank" rel="noreferrer" className="logo-window" aria-label="Shun Hing College official website"><img src="/shc-logo.png" alt="Shun Hing College, HKU"/></a>
  <div className="sidebar-title">Your college companion</div>
  <button className="new-chat" onClick={()=>{setMessages([]);setQuestion('');go('chat');input.current?.focus();}} disabled={busy}><Plus size={18}/> New conversation</button>
  <nav aria-label="Main navigation">
   <button className={view==='chat'?'active':''} onClick={()=>go('chat')}><MessageSquare size={19}/> Ask SHC <ChevronRight size={16}/></button>
   <button className={view==='library'?'active':''} onClick={()=>go('library')}><Library size={19}/> Source library <span className="count">{docs.length||'—'}</span></button>
   <button className={view==='manage'?'active':''} onClick={()=>go('manage')}><Settings2 size={19}/> Manage documents</button>
  </nav>
  <div className="sidebar-info"><BookOpen size={21}/><p>College life comes<br/>with questions.</p><span>Find your answer, and the official source behind it.</span></div>
  <div className="sidebar-bottom"><a href="https://shunhingcollege.hku.hk/" target="_blank" rel="noreferrer">Shun Hing College <ArrowUpRight size={15}/></a><a href="https://jockeyv3.hku.hk/" target="_blank" rel="noreferrer">JCSV III website <ArrowUpRight size={15}/></a><div className="university">The University of Hong Kong</div></div>
 </aside>
 <div className="workspace">
  <header className="topbar"><div><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={21}/></button><span className="breadcrumb">Shun Hing College</span><ChevronRight size={14}/><strong>{view==='chat'?'Student help desk':view==='library'?'Source library':'Manage documents'}</strong></div><span className="preview-label">Preview</span></header>
  <div className="workarea"><main id="main" className={'main '+(view==='chat'?'chat-main':'')}>
   {error&&<div className="error-notice" role="alert">{error} <button onClick={()=>void refresh()}>Retry</button></div>}
   {view==='chat'&&<>
    <div className="chat-scroll">
    {!messages.length?<section className="welcome"><div className="assistant-mark" aria-hidden="true"><MessageSquare size={29}/></div><div className="welcome-label">ASK SHC</div><h1>A little clarity<br/>for college life.</h1><p>Ask about Shun Hing College and JCSV III.<br/>Get answers grounded in college documents.</p><div className="suggestions">{suggestions.map((s,i)=><button key={s} onClick={()=>void ask(s)}><span className="suggestion-icon">{i===0?<ShieldCheck size={18}/>:i===1?<BookOpen size={18}/>:i===2?<HelpCircle size={18}/>:<FileText size={18}/>}</span>{s}<ArrowUpRight size={16}/></button>)}</div></section>:<div className="conversation">{messages.map((m,i)=><article key={i} className={'message '+m.role}><div className="message-label">{m.role==='user'?'You':<><span className="mini-mark"><MessageSquare size={14}/></span>Ask SHC{m.mode==='document-only'&&<span className="document-mode"><BookOpen size={13}/> Document-only mode</span>}{m.error&&<span className="answer-status">Couldn’t complete answer</span>}</>}</div><div className="message-body">{answerText(m.content,m.sources)}</div>{m.excerpts?.map((excerpt,n)=><section className="quoted-evidence" key={n}><button onClick={()=>setSelected(m.sources?.[excerpt.sourceIndex-1]||null)}><BookOpen size={15}/>{excerpt.title}<span className="citation">{excerpt.sourceIndex}</span></button><blockquote>{excerpt.text}</blockquote></section>)}{m.sources?.length?<div className="source-chips">{m.sources.map((s,n)=><button key={s.id+n} onClick={()=>setSelected(s)}><span>{n+1}</span>{s.title.length>42?s.title.slice(0,42)+'…':s.title}</button>)}</div>:null}{m.role==='assistant'&&<ModelAttempts message={m}/>}{m.role==='assistant'&&<div className="message-actions">{m.model&&<span className="model-label">{m.model.includes('gemma')?'Gemma 4 31B':'Qwen3.8 27B'} · Free{m.fallbackUsed?' · Fallback':null}</span>}<button onClick={async()=>{try{await navigator.clipboard.writeText(m.content+(m.excerpts?.length?"\n\n"+m.excerpts.map(e=>e.text+" ["+e.sourceIndex+"]").join("\n\n"):""));setCopied(i);setTimeout(()=>setCopied(-1),1800);}catch{setCopied(-1);}}}>{copied===i?<Check size={14}/>:<Copy size={14}/>} {copied===i?'Copied':'Copy answer'}</button>{m.error&&<button onClick={()=>void ask(messages[i-1]?.content||'')}>Try again</button>}</div>}</article>)}{busy&&<div className="thinking" role="status"><LoaderCircle size={18} className="spin"/> Checking college documents and preparing your answer…</div>}<div ref={end}/></div>}
    </div>
    <div className="composer-area"><form className="composer" onSubmit={e=>{e.preventDefault();void ask(question);}}><textarea ref={input} aria-label="Your question" placeholder="What would you like to know?" value={question} maxLength={1500} rows={2} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(question);}}}/><div className="composer-footer"><span><BookOpen size={14}/> Answers with sources</span><button className="send" type="submit" disabled={busy||!question.trim()} aria-label="Send question">{busy?<LoaderCircle size={20} className="spin"/>:<ArrowUp size={21}/>}</button></div></form><p className="fine-print">AI can make mistakes. Check the cited documents for the official wording.</p></div>
   </>}
   {view==='library'&&<div className="page-content"><div className="page-heading"><div><span className="section-label">THE KNOWLEDGE BASE</span><h1>Every answer starts here.</h1><p>Official pages, regulations and resident resources. Explore the collection behind Ask SHC.</p></div></div><div className="library-summary"><span><strong>{docs.length}</strong> sources</span><span><strong>{docs.filter(d=>d.kind==='PDF').length}</strong> PDFs</span><span><strong>{docs.reduce((n,d)=>n+(d.chunks||0),0)}</strong> searchable excerpts</span></div><div className="library-controls"><label className="search-field"><Search size={18}/><input aria-label="Search sources" placeholder="Search the source library" value={filter} onChange={e=>setFilter(e.target.value)}/></label><select aria-label="Filter sources" value={category} onChange={e=>setCategory(e.target.value)}>{['All sources','SHC','JCSV III','Rules & regulations','Admissions & fees','Facilities & services','Contacts & support','Uploaded'].map(c=><option key={c}>{c}</option>)}</select></div><div className="results-label">{shown.length} sources <span>Collected 19 September 2026</span></div><div className="document-list">{shown.map(d=><button className="document-row" key={d.id} onClick={()=>setSelected(d)}><span className="document-icon">{d.kind==='PDF'?<FileText size={20}/>:<Globe size={20}/>}</span><span><strong>{d.title}</strong><small>{d.organization} · {d.category}{d.historical?' · Historical / date-sensitive':''}</small></span><span className="file-kind">{d.kind}</span><ChevronRight size={17}/></button>)}{!shown.length&&<p className="empty">No sources match. Try another search or filter.</p>}</div></div>}
   {view==='manage'&&<div className="page-content manage"><span className="section-label">KEEP THE ANSWERS INFORMED</span><h1>Add to the knowledge base.</h1><p>Upload college notices, handbooks or updated rules. Documents become available to the chatbot immediately after processing.</p><form onSubmit={upload}><div className="admin-access"><ShieldCheck size={22}/><div><label htmlFor="token">Administrator access</label><p>Your access token is held only for this session.</p><input id="token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="Enter administrator token" required/></div></div><label className="field-label" htmlFor="doc-title">Document title <span>optional</span></label><input id="doc-title" className="text-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Resident handbook 2026–27" maxLength={160}/><label className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFile(e.dataTransfer.files[0]||null);}}><Upload size={28}/><strong>{file?file.name:'Choose a document or drop it here'}</strong><span>PDF, TXT or Markdown · Up to 5 MB</span><input type="file" accept=".pdf,.txt,.md" aria-label="Choose document" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p className="upload-note">Use searchable PDFs. Scanned documents need OCR first. Upload only material students are allowed to read; excerpts and uploaded files will be accessible to chatbot users.</p><button className="primary-button" disabled={uploading||!file||!token} type="submit">{uploading?<LoaderCircle size={17} className="spin"/>:<Plus size={18}/>} {uploading?'Reading and indexing…':'Add document'}</button><p className="upload-result" role="status">{notice}</p></form><h2>Uploaded documents</h2>{docs.filter(d=>d.organization==='Uploaded').length?docs.filter(d=>d.organization==='Uploaded').map(d=><div className="uploaded-row" key={d.id}><FileText size={19}/><span>{d.title}</span>{pendingDelete===d.id?<><button onClick={()=>void remove(d.id)}>Confirm removal</button><button onClick={()=>setPendingDelete(null)}>Cancel</button></>:<button disabled={!token} aria-label={'Remove '+d.title} onClick={()=>setPendingDelete(d.id)}><Trash2 size={17}/></button>}</div>):<p className="empty">Your uploaded documents will appear here. The official website collection is already in the library.</p>}</div>}
  </main>
  <aside className={'source-rail '+(selected?'has-selection':'')} aria-label="Source details">
   {selected?<><div className="rail-heading"><span>Source details</span><button aria-label="Close source details" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="source-detail"><span className="source-org">{selected.organization} · {selected.kind}</span><h2>{selected.title}</h2>{selected.page&&<p>Page {selected.page}</p>}<p className="source-date">Collected {selected.retrievedAt}{selected.updatedLabel&&<><br/>Source revision: {selected.updatedLabel}</>}</p>{selected.historical&&<div className="date-warning">This source is historical or date-sensitive. Check the academic year and any newer notices.</div>}{selected.text?<><h3>Retrieved excerpt</h3><blockquote>{selected.text}</blockquote></>:<p className="source-date">{selected.chunks} searchable excerpts · {selected.characters?.toLocaleString()} characters</p>}<a className="source-link" href={selected.url+(selected.page&&selected.url.startsWith('http')?'#page='+selected.page:'')} target="_blank" rel="noreferrer">Open original source <ArrowUpRight size={16}/></a></div></>:<><div className="rail-heading"><span>{recentSources.length?'Sources for this answer':'Rooted in official sources'}</span><BookOpen size={17}/></div>{recentSources.length?<div className="rail-sources">{recentSources.map((s,i)=><button key={s.id+i} onClick={()=>setSelected(s)}><span>{i+1}</span><div><strong>{s.title}</strong><small>{s.organization}{s.page?' · Page '+s.page:''}</small></div><ChevronRight size={15}/></button>)}</div>:<><p className="rail-intro">A helpful answer should come with somewhere to check it.</p><button className="source-origin" onClick={()=>{setCategory('SHC');go('library');}}><span className="origin-icon">SHC</span><span><strong>Shun Hing College</strong><small>College life, rules & admissions</small></span><ChevronRight size={15}/></button><button className="source-origin" onClick={()=>{setCategory('JCSV III');go('library');}}><span className="origin-icon village">III</span><span><strong>JCSV III</strong><small>Village facilities & regulations</small></span><ChevronRight size={15}/></button><div className="rail-topics"><h2>What you can ask about</h2>{['Rules & visitors','Facilities & everyday life','Admissions & fees','College teams & activities'].map(t=><div key={t}><Check size={15}/>{t}</div>)}</div><div className="collection-note"><span className="collection-line"/><strong>{docs.length||'…'} sources, one place.</strong><p>Collected from the official college and village websites. Sources retain their dates so older information stays in context.</p><button onClick={()=>go('library')}>Explore the library <ArrowUpRight size={15}/></button></div></>}<div className="rail-footer"><ShieldCheck size={18}/><p>A student information tool.<br/>College documents remain authoritative.</p></div></>}
  </aside></div>
 </div></div>;
}
